# Generated by Django 4.2.11 on 2024-05-01 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_remove_userprofile_date_userprofile_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiding_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hidden_user')},
            },
        ),
    ]
