# Generated by Django 4.2.11 on 2024-05-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_hiddenprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenprofile',
            name='hide_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hiddenprofile',
            name='hidden_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_profile', to='login.userprofile'),
        ),
    ]
