# Generated by Django 4.2.11 on 2024-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_hiddenprofile_hide_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
