# Generated by Django 4.2.11 on 2024-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_userprofile_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
