# Generated by Django 4.2.11 on 2024-05-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_userprofile_contact_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact_info',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_social_media',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
