# Generated by Django 4.2.11 on 2024-05-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_contact_info_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
