# Generated by Django 4.2.11 on 2024-05-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_hiddenprofile_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiddenprofile',
            name='is_deleted',
        ),
    ]
