# Generated by Django 4.2.11 on 2024-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_hiddenprofile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
