# Generated by Django 4.2.11 on 2024-05-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommendation_score',
            field=models.FloatField(default=0),
        ),
    ]
